name: pet
description: petService

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  path:
  path_provider: ^2.0.2
  provider: ^6.0.5
  supabase_flutter: ^1.10.6
  flutter_native_splash:
  adaptive_components: ^0.0.9
  timeago: ^3.5.0
  intl: ^0.18.1
  flutter_secure_storage:
  shared_preferences:
  permission_handler: ^10.2.0
  zego_uikit_prebuilt_call: ^3.16.0
  kakao_flutter_sdk: ^1.6.1
  image_picker: ^1.0.4
  change_app_package_name: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/WITDOG_Logo.png
    - assets/logo/kakao_login.png
    - assets/image/chat_image.png
    - assets/image/dogLang_image.png
    - assets/image/dogList_image.png
    - assets/image/main_image.png
    - assets/image/video_chat_image.png
    - assets/image/dog_video_call.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
